resources:
  - url: http://127.0.0.1:5000/sensor-button-card.js
    type: module
views:
  - cards:
      - type: custom:sensor-button-card
        name: sensor-button Card Development
        entity: sun.sun
        test_gui: true
